### ISSUE TITLE
Not familar with Ruby I get this error

### ISSUE THREAD

**Issue by gaslitbytech** [sportngin/rds-pgbadger#5]
./rds-pgbadger.rb -e env1 -i prod-96-2
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ox (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./rds-pgbadger.rb:5:in `<main>'

I tried the following top comment for related issue, though no joy. 
http://stackoverflow.com/questions/24652996/homebrew-not-working-on-osx

**Comment by mjlangan** [comment]
Also not a Ruby dev, but `gem install ox` and `gem install aws-sdk-core` (installing the script's third-party dependencies, basically) unblocked me.
